description: Technology stacks aimed to the java world
name: jland
display-name: jland
picture: "stack.png"
category: Backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility: # Put a list of technologies compatible with the stack
  - java
technologies:  # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologiess
  - Docker
  - Java
  - Springboot
about: docs/about.md
use-cases:
  - title: Use Case Title
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml
