version: '3.3'
services:
  ms-{{project_name}}:
    image: {{project_name}}
    restart: always
    environment:
      SERVER_PORT: 8080
    build: .
    networks:
      - app-{{project_name}}
networks:
  app-{{project_name}}:
    driver: bridge

